# -*- coding: utf-8 -*-
"""line_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWO0Y-psTqxVSRUyKJdHpa_It_oP3XbB
"""

from flask import Flask,request,abort
from linebot import LineBotApi,WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent,TextMessage,TextSendMessage
import pya3rt

app = Flask(__name__)

line_bot_api = LineBotApi('q1pb6qO0vf/VuaSJxXvqcBKgXV+Tw5aE3jvAy0hFl/9q3TMA9LaP3\
YyMoZbIIHeuvLyrkt/gYGNrzY3TDU+04bTHgAbYb89rLA1dbf+w/cLS+BFUO/gc5opzZfnaOXtDsh7ED52eEK1Y6aLyHWGZ3AdB04t89/1O/w1cDnyilFU=')

handler = WebhookHandler('9f6a8339598f51d31e57fa4ec578ac05')

@app.route("/callback",methods=['POST'])
def callback():
  signature = request.headers["X-Line-Signature"]
  body = request.get_data(as_text=True)

  try:
    handler.handle(body, signature)
  except InvalidSignatureError:
    abort(400)

  return 'OK'

@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
  api_message = talk_api(event.message.text)
  line_bot_api.reply_message(event.reply_token, TextSendMessage(text=api_message))

def talk_api(word):
  apikey="DZZqQxYUbFTIEj0sIhPCs9V7AaafOnLI"
  client = pya3rt.TalkClient(apikey)
  reply_message = client.talk(word)
  return reply_message['results'][0]['reply']

if __name__ == '__main__':
  app.run()


# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/'My Drive'/'linebot'